import { title } from 'process';

export const sectionsArray = [
  {
    id: 'main',
    background: '/images/back-0.jpg',
    title: 'main',
    description: 'none',
    image1: '/images/back-0.jpg',
    image2: '/images/back-1.jpg',
    image3: '/images/back-2.jpg',
    image4: '/images/back-3.jpg',
    imageArr: {
      image1: {
        image1: '/images/back-0.jpg',
        image2: '/images/back-1.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
      image2: {
        image1: '/images/back-2.jpg',
        image2: '/images/back-1.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
      image3: {
        image1: '/images/back-1.jpg',
        image2: '/images/back-1.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
      image4: {
        image1: '/images/back-0.jpg',
        image2: '/images/back-2.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
    },
  },
  {
    id: 'description',
    background: '/images/lightcaves.png',
    title: 'description',
    description: 'none',
    image1: '/images/back-0.jpg',
    image2: '/images/back-1.jpg',
    image3: '/images/back-2.jpg',
    image4: '/images/back-3.jpg',
    imageArr: {
      image1: {
        image1: '/images/back-0.jpg',
        image2: '/images/back-1.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
      image2: {
        image1: '/images/back-2.jpg',
        image2: '/images/back-1.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
      image3: {
        image1: '/images/back-1.jpg',
        image2: '/images/back-1.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
      image4: {
        image1: '/images/back-0.jpg',
        image2: '/images/back-2.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
    },
  },
  {
    id: 'section0',
    background: '/images/back-0.jpg',
    title: 'Breathtaking Story',
    description: `Explore the world of The Hobbit in the most immersive way that you could ever imagine! 
      Conquer the Lonely Mountain and help Thorin and 13 dwarves return the Heart of the Mountain.
     Middle-Earth awaits for you.`,
    image1: '/images/back-0.jpg',
    image2: '/images/back-1.jpg',
    image3: '/images/back-2.jpg',
    image4: '/images/back-3.jpg',
    imageArr: {
      image1: {
        image1: '/images/back-0.jpg',
        image2: '/images/back-1.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
      image2: {
        image1: '/images/back-2.jpg',
        image2: '/images/back-1.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
      image3: {
        image1: '/images/back-1.jpg',
        image2: '/images/back-1.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
      image4: {
        image1: '/images/back-0.jpg',
        image2: '/images/back-2.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
    },
  },
  {
    id: 'section1',
    background: '/images/back-1.jpg',
    title: 'The Battles!',
    description: `Help Bilbo fight all these creepy Goblins, Spiders, Stone Giants and much more evil creatures. 
    You would better be prepared for a hard battle!`,
    image1: '/images/back-0.jpg',
    image2: '/images/back-1.jpg',
    image3: '/images/back-2.jpg',
    image4: '/images/back-3.jpg',
    imageArr: {
      image1: {
        image1: '/images/back-0.jpg',
        image2: '/images/back-1.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
      image2: {
        image1: '/images/back-2.jpg',
        image2: '/images/back-1.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
      image3: {
        image1: '/images/back-1.jpg',
        image2: '/images/back-1.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
      image4: {
        image1: '/images/back-0.jpg',
        image2: '/images/back-2.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
    },
  },
  {
    id: 'section2',
    background: '/images/back-2.jpg',
    title: 'Unique Levels',
    description: `Carefully designed levels will immerse you completely in the story. 
    Extended levels with original cut content that was not seen in public before. With huge love from our modders ❤️`,
    image1: '/images/laketown-0.jpg',
    image2: '/images/back-1.jpg',
    image3: '/images/back-2.jpg',
    image4: '/images/back-3.jpg',
    imageArr: {
      image1: {
        image1: '/images/laketown-0.jpg',
        image2: '/images/laketown-0.jpg',
        image3: '/images/laketown-0.jpg',
        title: 'Lake Town',
        desc: `Lake-town, known as Esgaroth, thrived upon the Long Lake, built on wooden stilts over the water. Its origins traced back to ancient traders and fishermen who discovered its fertile shores.
              Under the rule of the Master, a savvy leader driven by profit, Lake-town prospered through trade with Dale and distant lands. Fishermen cast nets at dawn, craftsmen fashioned boats and barrels, and children played amidst the narrow streets.
              During festivals, music filled the air, and the scent of roasted meats mingled with laughter. Yet, beneath the surface of prosperity lingered unease as whispers of the dragon Smaug's return spread fear among the townsfolk.
              Despite these worries, Lake-town endured, drawing strength from its resilient community and deep-rooted traditions, a vital part of Middle-earth's rich tapestry.`,
      },
      image2: {
        image1: '/images/boob-0.jpg',
        image2: '/images/boob-1.jpg',
        image3: '/images/boob-2.jpg',
        title: 'Barrels out of Bonds',
        desc: `Deep within Mirkwood Forest, nestled amidst ancient trees and the whispering of leaves, 
              lies the Elvenking's palace. Built with graceful arches and adorned with intricate carvings, 
              this serene yet secretive stronghold serves as the heart of the Woodland Realm.
              Here, the air is perfumed with the scent of moss and the earthy essence of the forest, 
              creating an atmosphere of timeless tranquility tinged with an undercurrent of caution. 
              Silent guardians, elves of unmatched grace and vigilance, patrol the labyrinthine corridors
              and shadowed alcoves, their presence blending seamlessly with the ethereal beauty of their surroundings.`,
      },
      image3: {
        image1: '/images/back-1.jpg',
        image2: '/images/back-1.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
      image4: {
        image1: '/images/back-0.jpg',
        image2: '/images/back-2.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
    },
  },
  {
    id: 'section3',
    background: '/images/back-3.jpg',
    image1: '/images/back-0.jpg',
    image2: '/images/back-1.jpg',
    image3: '/images/back-2.jpg',
    image4: '/images/back-3.jpg',
    imageArr: {
      image1: {
        image1: '/images/back-0.jpg',
        image2: '/images/back-1.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
      image2: {
        image1: '/images/back-2.jpg',
        image2: '/images/back-1.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
      image3: {
        image1: '/images/back-1.jpg',
        image2: '/images/back-1.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
      image4: {
        image1: '/images/back-0.jpg',
        image2: '/images/back-2.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
    },
  },
  {
    id: 'playnow',
    background: '/images/lightcaves.png',
    image1: '/images/back-0.jpg',
    image2: '/images/back-1.jpg',
    image3: '/images/back-2.jpg',
    image4: '/images/back-3.jpg',
    imageArr: {
      image1: {
        image1: '/images/back-0.jpg',
        image2: '/images/back-1.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
      image2: {
        image1: '/images/back-2.jpg',
        image2: '/images/back-1.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
      image3: {
        image1: '/images/back-1.jpg',
        image2: '/images/back-1.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
      image4: {
        image1: '/images/back-0.jpg',
        image2: '/images/back-2.jpg',
        image3: '/images/back-2.jpg',
        title: 'Lake Town',
        desc: 'Soosos',
      },
    },
  },
];
